///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesArrowDown = 'assets/images/arrow-down.svg';
  static const String imagesArrowRight = 'assets/images/arrow-right.svg';
  static const String imagesBalance = 'assets/images/balance.svg';
  static const String imagesCardBackground = 'assets/images/card_background.svg';
  static const String imagesDashboard = 'assets/images/dashboard.svg';
  static const String imagesExpenses = 'assets/images/expenses.svg';
  static const String imagesGallery = 'assets/images/gallery.svg';
  static const String imagesImage1 = 'assets/images/image1.svg';
  static const String imagesImage2 = 'assets/images/image2.svg';
  static const String imagesIncome = 'assets/images/income.svg';
  static const String imagesLogout = 'assets/images/logout.svg';
  static const String imagesMyInvestments = 'assets/images/my_investments.svg';
  static const String imagesMyTransactions = 'assets/images/my_transactions.svg';
  static const String imagesSetting = 'assets/images/setting.svg';
  static const String imagesStatistics = 'assets/images/statistics.svg';
  static const String imagesWalletAccount = 'assets/images/wallet_account.svg';

}
